language: python
cache:
  - pip: true
  - node_modules # NPM packages

python:
  - 3.6

addons:
  chrome: stable
  postgresql: "9.6"

services:
  - postgresql

install:
  - npm install
  - npm run build
  - wget -N http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - psql -c "CREATE USER todoscheduler WITH ENCRYPTED PASSWORD 'todoscheduler' CREATEDB;" -U postgres

script:
  - ./run_ui_tests

after_success:
  - tar -czf dist.tar.gz dist

deploy:
  provider: releases
  api_key:
    secure: Eah9Gwr9/AOf8ggcy4jjMD2I1FUygQTIgVbwZcn0lHE/xB9I3O6vOmyHSdO3RrOGivpNW3Kj8CWpaxdDWHkxI5NNMT5Et6kcBvnIxCzEe1amocxiYqwVPLQ7SmuTWPue5aV9PPdmUoy+FYisbY+WMNFxvFQMQ2yEPXwZhtRhBUcxaTCGUQr/gaAmsuuYaCp3Vm+3gzqajz7Bgi0ZBRLRDgGW1JpIU/AWnNIgMfhO9mCMIK6N9rm50Vf2s+WUEyL1fS0Yr7slb62ulMXKIFwwtEpgRHOe5qcV4OmdSMhZ9JuinJ7SKgozHYnsgSmiz9jgIhrbF4r/fIQ4asqroS8zNylnNN8AaXgYlJTqq1CscQOHwlIbA24ZIuo9YpemVgcjEEV2Fn5KmbCD9DbsYG6/bDSWN4dEpwlRE3ALDgl9noyky8K/mff5uNY6GgNveN9m6Lov84/pReg6yBwKwmrwKuJ8+RRlBx+j8LLzQ8eQWaUyJGkfdZmfMPKuX9tqhzFYgN59fubJghv3JvrYowfHDPyupkS36WzEPrvCZCn1g6jut51ikvM3Pt15lq5sVWoyfW6WSZMDA3OkrF7hwF0eawPEose2hH+DNbxAjIxcpfDuXLGpb436F7zs5eoYkHdnhqrqIUmi56Nayd04VLxCnDIl4TPO7CB0ppFlUyTq/lA=
  file: dist.tar.gz
  skip_cleanup: true
  on:
    tags: true
