#!/bin/sh -e
TMPDIR=`mktemp -d`

DISTDIR=`pwd`/dist
TESTDIR=`pwd`/uitests

GITHUB_API_URL=https://api.github.com
if [ -n "$GITHUB_API_AUTH" ];
then
  # use the provided auth token to avoid running into the rate limit
  GITHUB_API_URL=https://${GITHUB_API_AUTH}@api.github.com
fi

MINOR_API_VERSION=`cat API_VERSION`
API_VERSION=${MINOR_API_VERSION}.$(curl -s $GITHUB_API_URL/repos/wichmannpas/todoscheduler/releases | jq -r '.[].tag_name' | grep "^v${MINOR_API_VERSION}" | cut -d. -f3 | sort -n | tail -n1)

echo Using API version ${API_VERSION}

cd $TMPDIR

wget -O- https://github.com/wichmannpas/todoscheduler/archive/v${API_VERSION}.tar.gz | tar -xz --strip-components=1

ln -s $TESTDIR

pip install pip-tools
pip-compile --output-file requirements-testing.txt requirements-testing.in requirements.in
pip install -r requirements-testing.txt
pip install selenium
pip install psycopg2-binary

cp todoscheduler/settings.py.example.postgres todoscheduler/settings.py
sed -i "s/INSTALLED_APPS = \\[/INSTALLED_APPS = ['uitests',/" todoscheduler/settings_base.py

DIST_DIR=$DISTDIR exec ./manage.py test uitests
