const API_URL = 'http://127.0.0.1:8000'

const USE_LEGAL_STATEMENT = true
const OPERATOR_ADDRESS = 'John Doe\nFoo Street 42\n1337 Bar City\nGermany'

const TEXTAREA_MIN_ROWS = 3
const TEXTAREA_MAX_ROWS = 25

export {
  API_URL,
  TEXTAREA_MIN_ROWS,
  TEXTAREA_MAX_ROWS,
  USE_LEGAL_STATEMENT,
  OPERATOR_ADDRESS
}
